### ISSUE TITLE
Request additional term for harvest service

### ISSUE THREAD

**Issue by narock** [ec-geolink/glharvest#4]
The void spec is somewhat ambiguous on the meaning of void:dataDump. However, it is often understood to be a full data dump. Can we create another term to be used for partial/incremental dumps? Perhaps as a subproperty of void:dataDump to clearly distinguish the two cases?

**Comment by amoeba** [comment]
Good catch. We definitely need to make this distinction.

What do you think about using `void:TechnicalFeature` to make our distinction, which has the description:

> The property of void:feature can be used for expressing certain technical features of a dataset, such as its supported RDF serialization formats

The [features section of the spec](http://www.w3.org/TR/void/#features)  gives an example usage of:

``` ttl
:HTTPCachingETags a void:TechnicalFeature;
    rdfs:label "HTTP ETag support";
    rdfs:comment "the dataset supports HTTP caching using ETags";
    rdfs:seeAlso <http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#>;
    .
```

Since `void:dataDump` is technically defined as:

> An RDF dump, partial or complete, of a `void:Dataset`.

it'd be nice to follow the spec. Given your experience, do you think following the spec would be confusing?

So full dumps and partial dumps would need to be separate `void:Dataset`s, each with their own `void:dataDump` and `void:feature` `void:TechnicalFeature` statement, where the `void:TechnicalFeature` is one of two named individuals we create, one for full dumps and one for partial dumps.

I can write this up in the proposal today so you can take a look.

Thanks for bring this up!

**Comment by mbjones** [comment]
@amoeba That looks like a great approach to me, and nice and simple.

**Comment by narock** [comment]
Looks good to me too. Thanks @amoeba for putting this together. As you mention, void:dataDump is a partial or complete dump. I can envision this data being used by several services and it would be helpful if a query could unambiguously determine which was being offered. It would have implications for what they do with the data dump. I think your proposal solves that.

**Comment by amoeba** [comment]
I've updated the proposal: https://github.com/ec-geolink/glharvest/blob/master/proposal.md

For the terms, I've proposed DataOne host a mini-ontology with two `void:TechnicalFeature` resources, one for each concept, full or partial dumps. It'll look very much like the `HTTPCachingETags` example above.

Providers will maintain a VoID file at their location which uses the two named individuals from this ontology. There's a little more detail in the proposal and I'd love feedback.

**Comment by narock** [comment]
The updated proposal looks good. Thanks for putting this together. The only outstanding question for me is how we get updated graphs from the harvester service to the co-reference resolution team (and any other service that needs them). How involved would it be for the harvester service to output periodic data dumps? I think this would be much more efficient than trying to get all triples for a graph via the harvester's SPARQL endpoint.

**Comment by amoeba** [comment]
Great point. I'm not overly familiar with RDF and related technologies but it makes sense that making downstream services grab all providers' triples via SPARQL would be the wrong way to go about things.

Periodic dumps of the triple store makes sense. It wouldn't be sufficient to just publicly expose each providers' dump files after they are transferred to the harvester as some providers may be only providing update graphs. So the harvester service would need to provide full dumps of each named graph. I'm happy to add this to the proposal. How do daily dumps sound (for now)?

Thanks for catching it.

**Comment by narock** [comment]
I'm ok with daily. Although, we should check with @mbjones to see if that works on his end.

**Comment by amoeba** [comment]
Closing this issue as the the main issue was resolved by deciding on terms to use for these features.
