### ISSUE TITLE
Figure out what to do about providers specifying the name of their named graph

### ISSUE THREAD

**Issue by amoeba** [ec-geolink/glharvest#5]
The central triple store needs to put each provider's triples in its own named graph. Determining the name for this named graph can be done a few ways. The current proposal doesn't address this very well.

I think a named graph in a LOD graph should be an HTTP URI. Not sure. See http://www.w3.org/TR/sparql11-service-description/#example.

The options I see are:

**Option 1**

Use the provider's `void:dataDump` URI without the filename, e.g. http://lod.dataone.org/dataone.ttl would end up in a named graph of  http://lod.dataone.org/ .This doesn't give much flexibility but it also isn't so important what the actual name of the named graph is.

**Option 2**

Manually created a name for the named graph in the registry file. Not very flexible/elegant.

**Option 3**

Somehow use the [SPARQL Service Description](www.w3.org/TR/sparql11-service-description/) spec to let the providers specify their desired name for their named graph within their VoID file. I don't think it would be good to just add a property `sd:name` to their `void:Dataset`, e.g., 

``` ttl
:#d1lodfull a void:Dataset ;
  void:dataDump <http://lod.dataone.org/dataone.ttl> ;
  sd:name <http://lod.dataone.org/> ;
  .
```

as `sd:name` isn't supposed to be a property on `sd:NamedGraph`s. But this could be done.

**Option 4**

Make the providers provide a [SPARQL Service Description](www.w3.org/TR/sparql11-service-description/)  file instead that describes their dump:

``` ttl
:#thegraph 
  a sd:NamedGraph ;
  sd:name <http://www.example/named-graph> ;
  sd:graph [
      a sd:Graph, void:Dataset ;
      void:dataDump <http://lod.dataone.org/dataone.ttl> ;
  ] ;
  .
```

I'm not sure if it's okay to do the above but it would be a workable solution if it is.

**Comment by narock** [comment]
I agree Option 2 is not very elegant. However, it may be the easiest to implement. If I understand the workflow correctly, new data providers will have to contact the GeoLink team to inform us that they have a VoID file available and are ready to be harvested. There's then the manual step of adding the VoID location to the harvesting service. If may be most effective to just create a named graph URI at that point. This could be done in conjunction with the data provider or independently by us. Thus, registering with GeoLink involves creating a dump file, creating a VoID file, and contacting the GeoLink team to register your VoID location and created a named graph URI.

**Comment by amoeba** [comment]
> If I understand the workflow correctly, new data providers will have to contact the GeoLink team to inform us that they have a VoID file available and are ready to be harvested.

Yep, that's right.

> Thus, registering with GeoLink involves creating a dump file, creating a VoID file, and contacting the GeoLink team to register your VoID location and created a named graph URI.

Yeah, sounds good.

It seems like the [SPARQL query spec](http://www.w3.org/TR/rdf-sparql-query/#namedGraphs) says it's fine if the IRI for a named graph is also the HTTP-accessible URL for a serialization of that named graph. So it'd be fine to just use the IRI for the dump as the name of the named graph for now. 

Thanks for the feedback!
